=== manchalamounika/JavaTraining2014/divya/School program using Dom/school.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT school (class+)>
<!ELEMENT class (student*, teacher,subject*)>
<!ELEMENT student (name,dob,address)>
<!ELEMENT name (fname,lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT teacher (tname)>
<!ELEMENT tname (#PCDATA)>
<!ELEMENT subject (#PCDATA)>

<!ATTLIST school name CDATA #REQUIRED>
<!ATTLIST class standard CDATA #REQUIRED>
<!ATTLIST student id CDATA #REQUIRED>
<!ATTLIST subject sub_name CDATA #REQUIRED>

=== manchalamounika/JavaTraining2014/divya/School program using Dom/school.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE school SYSTEM "school.dtd">

<school name="Sri Sai">
  <class standard="tenth">
     <student id="01">
       <name>
         <fname>Divya</fname>
         <lname>Kalikota</lname>
       </name>
       <dob>1997/08/05</dob>
       <address>Karimnagar</address>	
     </student>	
     <student id="02">
       <name>
         <fname>vidhyu</fname>
         <lname>perla</lname>
       </name>
       <dob>1996/11/05</dob>
       <address>Karimnagar</address>	
     </student>
     <teacher>
       <tname>Binny</tname>
     </teacher>
     <subject sub_name="maths"/>
     <subject sub_name="science"/>
     <subject sub_name="english"/>
     <subject sub_name="telugu"/>
  </class>

  <class standard="ninth">
     <student id="03">
       <name>
         <fname>anamika</fname>
         <lname>kona</lname>
       </name>
       <dob>1998/10/13</dob>
       <address>Karimnagar</address>	
     </student>
     <student id="04">
       <name>
         <fname>niraja</fname>
         <lname>gourishetti</lname>
       </name>
       <dob>1999/06/13</dob>
       <address>Karimnagar</address>	
     </student>
     <teacher>
       <tname>Thomas</tname>
     </teacher>
     <subject sub_name="science"/>\
     <subject sub_name="english"/>
     <subject sub_name="telugu"/>
  </class>
</school>
