=== manchalamounika/JavaTraining2014/rohit/Schooldtls Parsing/School.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT School (School_Name,Class+)>
<!ELEMENT School_Name (#PCDATA)>
<!ELEMENT Class (Class_Name,Student+,Teacher,Subjects+)>
<!ELEMENT Class_Name (#PCDATA)>
<!ELEMENT Student (Name,DOB,Adress)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT DOB (#PCDATA)>
<!ELEMENT Adress (#PCDATA)>
<!ELEMENT Teacher (Teacher_Name)>
<!ELEMENT Teacher_Name (#PCDATA)>
<!ELEMENT Subjects (#PCDATA)>

=== manchalamounika/JavaTraining2014/rohit/Schooldtls Parsing/School.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE School SYSTEM "/home/valuelabs/workspace/parserprograms/src/com/vl/parserexamples/School.dtd">
<School>
	<School_Name>Hyderabad Public School</School_Name>
	<Class>
		<Class_Name>first_class</Class_Name>
		<Student>
			<Name>Rohit</Name>
			<DOB>1992-10-20</DOB>
			<Adress>Hyderabad</Adress>
		</Student>
		<Student>
			<Name>Srinu</Name>
			<DOB>1993-08-21</DOB>
			<Adress>Hyderabad</Adress>
		</Student>
		<Student>
			<Name>Mounika</Name>
			<DOB>1992-02-11</DOB>
			<Adress>Hyderabad</Adress>
		</Student>
		<Teacher>
			<Teacher_Name>Harisha</Teacher_Name>
		</Teacher>
		<Subjects>English</Subjects>
		<Subjects>Telugu</Subjects>
		<Subjects>Drawing</Subjects>
		<Subjects>Hindi</Subjects>
	</Class>
	<Class>
		<Class_Name>Second_Class</Class_Name>
		<Student>
			<Name>Nandini</Name>
			<DOB>1991-05-15</DOB>
			<Adress>Hyderabad</Adress>
		</Student>
		<Student>
			<Name>Praveen</Name>
			<DOB>1991-02-29</DOB>
			<Adress>Hyderabad</Adress>
		</Student>
		<Student>
			<Name>Himani</Name>
			<DOB>1992-12-29</DOB>
			<Adress>Hyderabad</Adress>
		</Student>
		<Teacher>
			<Teacher_Name>Harsha</Teacher_Name>
		</Teacher>
		<Subjects>English</Subjects>
		<Subjects>Telugu</Subjects>
		<Subjects>Social Studies</Subjects>
		<Subjects>Hindi</Subjects>
		<Subjects>Maths</Subjects>
	</Class>
</School>

=== manchalamounika/JavaTraining2014/shashikanth/SchoolXML/School.xml
<?xml version="1.0"?>
<!DOCTYPE School SYSTEM "/home/valuelabs/Programs/XML/School.dtd"> 
<School>
	<Class>
		<ClassName>Seventh</ClassName>
		<Student>
			<Name>Sachin</Name>
			<DOB>1991-04-02</DOB>
			<Address>Mumbai</Address>
		</Student>
		<Student>
			<Name>Dravid</Name>
			<DOB>1990-05-02</DOB>
			<Address>Banglore</Address>
		</Student>
		<Student>
			<Name>Kohli</Name>
			<DOB>1994-06-04</DOB>
			<Address>Delhi</Address>
		</Student>
		<Teacher>
			<Name>A</Name>
		</Teacher>
		<Subjects>
			<Name>English</Name>
			<Name>Science</Name>
			<Name>Telugu</Name>
		</Subjects>
	</Class>
	<Class>
		<ClassName>Tenth</ClassName>
		<Student>
			<Name>Dhoni</Name>
			<DOB>1991-04-01</DOB>
			<Address>Chennai</Address>
		</Student>
		<Student>
			<Name>Yuvi</Name>
			<DOB>1993-08-03</DOB>
			<Address>Punjab</Address>
		</Student>
		<Student>
			<Name>Raina</Name>
			<DOB>1996-10-06</DOB>
			<Address>Jaipur</Address>
		</Student>
		<Teacher>
			<Name>B</Name>
		</Teacher>
		<Subjects>
			<Name>Maths</Name>
			<Name>Physics</Name>
			<Name>Chemistry</Name>
		</Subjects>
	</Class>
</School>
